### ISSUE TITLE
BaseTypeHint isn't honored if a class is renamed via ClassNameHint

### ISSUE THREAD

**Issue by michaelcfanning** [Microsoft/jschema#52] opened 2018-10-11 23:07 UTC
```
  "exception": [
    {
      "kind": "ClassNameHint",
      "arguments": {
        "className": "ExceptionData"
      }
    },
    {
      "kind": "BaseTypeHint",
      "arguments": {
        "baseTypeNames": [
          "PropertyBagHolder"
        ]
      }
    }
  ],
```

**Comment by lgolding** [comment] 2018-10-17 21:31
@michaelcfanning This is by design, although you could argue that the design isn't as easy to use as it should be. To get this to work, you need to file any hints that affect the renamed class _under the new class name_. `BaseTypeHint` isn't the only hint that's affected. To fix this, your `CodeGenHints.json` needs to look like this:

```
  "exception": [
    {
      "kind": "ClassNameHint",
      "arguments": {
        "className": "ExceptionData"
      }
    }
  ],
  "exceptionData": [
    {
      "kind": "BaseTypeHint",
      "arguments": {
        "baseTypeNames": [
          "PropertyBagHolder"
        ]
      }
    }
  ],
```

Another nit in the design is that the renamed class has to appear in camelCase in the hints file. In the example above, note that the dictionary key is `exceptionData`, even though the renamed class is `ExceptionData`.

I added a unit test to demonstrate this. I'll close this issue once the PR is merged.

**Comment by michaelcfanning** [comment] 2018-10-17 21:36
makes sense, i'll fix this in our codegen file. thanks for taking a look.

**Comment by lgolding** [comment] 2018-10-18 21:04
PR is merged; issue closed.

**Closed** 2018-10-18 21:04 UTC
Labels: area-code-gen, bug, resolved-by-design
